/** @aigos/database — Phase 0 step 3 (S3; I5/I8/I9; ADR-019/043/046). */
export { withWorkspace, withWorkspaceOnClient, withUser, dangerouslyUnscoped } from "./tenancy.js";
export type { Tx } from "./tenancy.js";
export { applyMigrations, MIGRATIONS_DIR } from "./migrate.js";
export { PgConfigStore } from "./config-store.js";
export { MembershipRepository } from "./repositories/memberships.js";
export type { Membership, MembershipRole } from "./repositories/memberships.js";
export { ConnectionRepository } from "./repositories/connections.js";
export type { Connection } from "./repositories/connections.js";
export { listEnabledSystemJobs, scheduleWorkspaceJob, recordJobRun } from "./repositories/scheduled-jobs.js";
export type { ScheduledJobRow } from "./repositories/scheduled-jobs.js";
export { provisionOnSignIn, isMember, listUserWorkspaces } from "./provisioning.js";
export type { ProvisionedIdentity } from "./provisioning.js";
export { SignalRepository } from "./repositories/signals.js";
export type { SignalDraft } from "./repositories/signals.js";
export { TokenVault } from "./vault.js";
export type { StoredTokens, VaultKey } from "./vault.js";
export { getSyncState, updateSyncState } from "./repositories/sync-state.js";
export type { SyncState, SyncStateUpdate } from "./repositories/sync-state.js";
export { updateConnectionHealth } from "./repositories/connection-health.js";
export type { HealthTransition } from "./repositories/connection-health.js";
export type { ConnectionHealth } from "./repositories/connections.js";
